#general_settings:
  #database_connection_pool_limit: 20

model_list:
  - model_name: mistral-small-latest
    litellm_params:
      model: mistral/mistral-small-latest
      api_key: Zh45P0D2DtbLM5vEfs8RMBnOpEMWdrrQ

#litellm_settings:
  #drop_params: True
  #success_callback: ["prometheus"]
  #failure_callback: ["prometheus"]
  #service_callback: ["prometheus_system"]

